workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - env_secrets # Must include `unsplash_api`
      vars:
        APP_ID: "com.example.puzzle_game"
    scripts:
      - name: Generate .env from secure variables
        script: |
          echo "Generating .env file"
          echo "unsplash_api=$unsplash_api" > .env
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS Release
        script: |
          flutter clean
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
